### ISSUE TITLE
Avoid warning on ruby 2.2.2

### ISSUE THREAD

**Issue by filipegiusti** [minitest/minitest-gcstats#1]
minitest-gcstats-1.1.0/lib/minitest/gcstats.rb|11| warning: GC.stat keys were changed from Ruby 2.1. In this case, you refer to obsolete 'total_allocated_object' (new key is 'total_allocated_objects'). Please check https://bugs.ruby-lang.org/issues/9924 for more information.

**Comment by zenspider** [comment]
Fixed. Thanks!

**Comment by filipegiusti** [comment]
Thank you!

**Comment by filipegiusti** [comment]
Hmmm I tried to do

``` ruby
gem 'minitest-gcstats', git: 'https://github.com/seattlerb/minitest-gcstats.git',
  ref: '920c2c7e31c06131e0aca75618f03b4069810981' # '~> 1.2.0'
```

but it doesn't work.

Publishing a new version or adding a gemspec would solve the problem for me.

**Comment by zenspider** [comment]
> On May 8, 2015, at 15:17, Filipe Giusti notifications@github.com wrote:
> 
> Hmmm I tried to do
> 
> gem 'minitest-gcstats', git: 'https://github.com/seattlerb/minitest-gcstats.git'
> ,
> 
> ref: '920c2c7e31c06131e0aca75618f03b4069810981' # '~> 1.2.0'
> but it doesn't work.
> 
> Publishing a new version or adding a gemspec would solve the problem for me.

I'll publish on its normal schedule. Soon...

**Comment by filipegiusti** [comment]
Ok, thanks.
